# peer1 \u914D\u7F6E
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer1

server:
  port: 8081
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url.defaultZone: http://127.0.0.1:8082/eureka/,http://127.0.0.1:8083/eureka/

# peer2 \u914D\u7F6E
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer2
server:
  port: 8082
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8083/eureka/

# peer3 \u914D\u7F6E
spring:
  application:
    name: spring-cloud-eureka
  profiles: peer3
server:
  port: 8083
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8081/eureka/,http://127.0.0.1:8082/eureka/